
export let productData = [
    {
      key: 1,
      img: "../../assets/red.png",
      title: "Quilted Hooded Jacket",
      subTitle: "Finest Quality Hoodie",
      brand: "HighLander Collection",
      desc: "Stay cozy and stylish with the Comfort Fit Hoodie, your go-to for laid-back days and cool-weather outings. Made from ultra-soft, high-quality cotton blend fabric, this hoodie delivers warmth without sacrificing comfort.",
      price: 799,
      deletedPrice: 1299,
      discount: 12,
    },
    {
      key: 2,
      img: "../../assets/fea_1.png",
      title: "Exclusive Nike T-Shirt",
      subtitle: "Finest Quality T-Shirt",
      brand: "The Nike Brand",
      desc: "Stay stylish and comfortable with the Nike Essential T-shirt, perfect for casual wear or an active lifestyle. Made from premium, soft cotton fabric, this T-shirt offers a lightweight and breathable feel, ensuring all-day comfort.",
      price: 999,
      deletedPrice: 1599,
      discount: 20,
    },
    {
      key: 3,
      img: "../../assets/winter.png",
      title: "Stylish Winter Apparel",
      subtitle: "Blue Denim Jacket",
      brand: "H&M - A Fashion Brand",
      desc: "Experience ultimate comfort and style with the Puma Essential Jacket, designed to keep you warm and chic all season. Stay warm and stylish with the Puma Essential Jacket, perfect for layering during winter. Crafted from premium, soft cotton fabric, it provides a cozy and breathable feel.",
      price: 1499,
      deletedPrice: 2150,
      discount: 20,
    },
    {
      key: 4,
      img: "../../assets/denim2.png",
      title: "Classic Denim Jacket",
      subTiitle: "Trending Denim",
      brand: "H&M - A Fashion Brand",
      desc: "Elevate your wardrobe with the timeless appeal of the Classic Denim Jacket. Crafted from high-quality, durable denim, this jacket combines rugged style with modern versatility. Featuring a classic button-up front, chest pockets, and a comfortable fit.",
      price: 1399,
      deletedPrice: 1700,
      discount: 17,
    },
  ];